### ISSUE TITLE
Instructions are wrong

### ISSUE THREAD

**Issue by Dhar** [luxas/kubeadm-installer#1]
Should be:

`$ docker run -it -v /etc/cni:/rootfs/etc/cni -v /etc/systemd:/rootfs/etc/systemd -v /opt:/rootfs/opt -v /usr/bin:/rootfs/usr/bin luxas/kubeadm-installer ${your_os_here}`

**Comment by luxas** [comment]
Oops, readme got out of sync...
Do you wanna contribute :smile:?

**Comment by Dhar** [comment]
I can take a shot at helping out, although the reason I'm using `kubeadm` is because I'm learning more about Kubernetes.  Especially installation. :smile: Where is help needed?

**Comment by luxas** [comment]
I meant if you'd like to contribute a patch to the docs in this repo? :)
Also, it should be specified that it supports Ubuntu 16.04 and over only.

**Comment by Dhar** [comment]
Sorry, broke my hand at the end of this conversation and that occupied me with other things for awhile. :)

**Comment by luxas** [comment]
Oh how bad! Hope you're feeling better now :)
I ended up fixing it myself, but thanks for the heads up
