### ISSUE TITLE
socat missing for CoreOS

### ISSUE THREAD

**Issue by stephanlindauer** [luxas/kubeadm-installer#6]
preflight checks exit with:
```
core@ip-10-0-1-121 ~ $ sudo kubeadm init
Running pre-flight checks
preflight check errors:
	socat not found in system path
```

**Comment by luxas** [comment]
Yes, I know, but you can just ignore it, since kubelet runs inside an rkt fly container.
However, I've only gotten flannel to work as the pod network, on that side, CoreOS isn't stable unfortunately,
