### ISSUE TITLE
[coreos] Missing ${ROOTFS}

### ISSUE THREAD

**Issue by antoineco** [luxas/kubeadm-installer#8]
On Container Linux 1353.1.0 the script fails with:
```
/entrypoint.sh: line 97: /etc/systemd/network/50-cni.network: No such file or directory
Installed 50-cni.network in /etc/systemd/network/50-cni.network
(...)

core@kovh ~ $ ls -l /etc/systemd/network/
total 0
```
That's because of a missing `${ROOTFS}/` on the line `cat > /etc/systemd/network/50-cni.network`.

I can't send  PR because the script distributed with the `luxas/kubeadm-installer` on the Docker Hub doesn't match the script in the current repo.

**Comment by xakraz** [comment]
I think we can close this issue with the upcoming changes.

**Comment by luxas** [comment]
SGTM

**Comment by antoineco** [comment]
@xakraz could you clarify "upcoming changes"?

**Comment by xakraz** [comment]
@antoineco I was meaning the ones from #9
